### ISSUE TITLE
自画投稿【万物皆可像素画】之魔兽世界——巫妖王

### ISSUE THREAD

**Issue by dreamym07** [pixel32/Weekly_PixelartTutorials#3]
![01](https://user-images.githubusercontent.com/5978886/111941093-41d03f80-8b0b-11eb-947a-16572ffaea3d.png)
![02](https://user-images.githubusercontent.com/5978886/111941133-557ba600-8b0b-11eb-991b-f5f8ea258ee6.png)
![03](https://user-images.githubusercontent.com/5978886/111941136-59a7c380-8b0b-11eb-8f44-33ba39191a71.png)
![04](https://user-images.githubusercontent.com/5978886/111941138-5a405a00-8b0b-11eb-9922-0ac8835b5f1d.png)
![07](https://user-images.githubusercontent.com/5978886/111941140-5b718700-8b0b-11eb-913d-bd7083318901.png)
![08](https://user-images.githubusercontent.com/5978886/111941142-5c0a1d80-8b0b-11eb-8d58-e7f399313f9a.png)
![10](https://user-images.githubusercontent.com/5978886/111941145-5d3b4a80-8b0b-11eb-8fff-0c63031abeb8.gif)
![11](https://user-images.githubusercontent.com/5978886/111941149-61676800-8b0b-11eb-9bcb-e87a3fc903b1.gif)
![12](https://user-images.githubusercontent.com/5978886/111941154-64faef00-8b0b-11eb-8d1f-02a79b8a515d.gif)
![13](https://user-images.githubusercontent.com/5978886/111941159-65938580-8b0b-11eb-8d4f-722e3c56fbd7.gif)
![charactor](https://user-images.githubusercontent.com/5978886/111941174-6a583980-8b0b-11eb-8f10-5fd391878654.gif)

链接参考：https://www.bilibili.com/read/cv10342817

**Comment by pixel32** [comment]
厉害了！这个可以单发一篇。
